services:
  gazab-agency:
    image: ghcr.io/abdallahdalvi/gazab-engine:latest
    pull_policy: always
    container_name: gazab-agency
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "9740:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      PACKAGE_DATA_DIR: /app/data
    volumes:
      - ./data:/app/data
